import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ICONS_DIR = path.join(__dirname, '../Icons');
const OUTPUT_FILE = path.join(__dirname, '../src/icons.tsx');

function toPascalCase(filename) {
  // Remove .png extension and any other extensions (e.g., .svg.png)
  const name = filename.replace(/\.(png|svg|jpg|jpeg)$/g, '').replace(/\./g, '_');
  
  // Split by underscores, hyphens, or capital letters
  const parts = name
    .replace(/([A-Z])/g, ' $1')
    .split(/[\s_-]+/)
    .filter(Boolean);
  
  // Capitalize first letter of each part
  const pascalCase = parts
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
  
  return pascalCase;
}

function getAllPngFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  
  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    
    if (stat.isDirectory()) {
      getAllPngFiles(filePath, fileList);
    } else if (file.endsWith('.png')) {
      fileList.push(filePath);
    }
  });
  
  return fileList;
}

function generateIconsFile() {
  try {
    // Recursively get all PNG files from Icons directory
    const allFiles = getAllPngFiles(ICONS_DIR);
    
    console.log(`Found ${allFiles.length} icon files`);

    // Track export names to detect duplicates
    const exportNames = new Map();
    const imports = [];
    const components = [];
    
    // Generate imports and component definitions
    allFiles.forEach(filePath => {
      const filename = path.basename(filePath);
      // Get path from src directory to the icon file
      const srcDir = path.dirname(OUTPUT_FILE);
      const projectRoot = path.dirname(srcDir);
      const iconRelativePath = path.relative(projectRoot, filePath).replace(/\\/g, '/');
      const parentDir = path.basename(path.dirname(filePath));
      
      let exportName = toPascalCase(filename);
      
      // If there's a duplicate, prepend parent folder name
      if (exportNames.has(exportName)) {
        exportName = toPascalCase(parentDir + '_' + filename);
      }
      
      exportNames.set(exportName, filePath);
      const importName = `${exportName}Image`;
      
      imports.push(`import ${importName} from '../${iconRelativePath}';`);
      components.push(`export const ${exportName}: React.FC<Omit<IconProps, 'src'>> = (props) => <Icon src={${importName}} {...props} />;`);
    });

    // Sort imports and components
    imports.sort();
    components.sort();

    // Create the file content
    const content = `// This file is auto-generated by scripts/generate-icons.js
// Do not edit manually - run 'npm run generate-icons' to regenerate

import React from 'react';
import { Icon, IconProps } from './Icon';

${imports.join('\n')}

${components.join('\n')}
`;

    // Write to file
    fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
    console.log(`✓ Generated ${OUTPUT_FILE} with ${allFiles.length} icon components`);

  } catch (error) {
    console.error('Error generating icons file:', error);
    process.exit(1);
  }
}

generateIconsFile();
